apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gcp-secret
  title: Create GCP Secret
  description: Legt ein neues Secret im Google Cloud Secret Manager an
spec:
  owner: user:guest
  type: resource

  parameters:
    - title: Secret Details
      required:
        - secretId
        - projectId
      properties:
        secretId:
          title: Secret ID (Name)
          type: string
          description: Ein eindeutiger Name für das Secret
        projectId:
          title: GCP Project ID
          type: string
        labels:
          title: Labels
          type: object
          default: { "created-by": "backstage" }

  steps:
    - id: template
      name: Generating Secret Terraform
      action: fetch:template
      input:
        url: ./secret-content
        values:
          secretId: ${{ parameters.secretId }}
          projectId: ${{ parameters.projectId }}

    - id: publish
      name: Publishing to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: GCP Secret Infrastructure for ${{ parameters.secretId }}
        repoUrl: ${{ parameters.repoUrl }}
