apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.bucketName }}
  description: GCP Bucket created via Scaffolder
  annotations:
    google.com/project-id: my-gcp-project # Hier könnte man den Projektnamen dynamisch einsetzen
spec:
  type: bucket
  owner: user:guest
  system: gcp-infrastructure
